// Types for the collaborative viewer task system (Motivation Monday).
//
// Viewers are keyed by LOWERCASE USERNAME, matching how the community garden keys
// its participants. The incoming NormalizedChatMessage from lib/chat-commands.ts
// carries no Twitch user-id, so username is the only stable key available without
// modifying the shared chat path.

export type TaskStatus = "active" | "queued" | "cleared"

export interface ViewerTask {
  /** Lowercase username. Primary key. */
  userId: string
  /** Lowercase username, kept separate for clarity at call sites. */
  username: string
  /** Original cased display name, used in chat confirmations and on the card. */
  displayName: string
  /** Twitch chat color, only applied when readable on a dark card. */
  usernameColor?: string

  currentTask: string | null
  /** Most recent task ever submitted. Survives breaks and powers !repeat. */
  lastTask: string | null
  /** Task carried out of the work period that just ended, so !done still works. */
  lastWorkTask: string | null

  status: TaskStatus
  submittedAt: number
  completedToday: number
}

export interface ViewerTaskState {
  tasksByUser: Record<string, ViewerTask>
  /** Ordered list of userIds currently in the visible rotation. */
  rotationOrder: string[]
  enabled: boolean
}

/** A task resolved for display in the rotating card. */
export interface DisplayedTask {
  userId: string
  displayName: string
  usernameColor?: string
  task: string
}

/** Outgoing chat confirmation generated by a command. */
export interface TaskCommandResponse {
  userId: string
  displayName: string
  message: string
  timestamp: number
}

export const MAX_TASK_LENGTH = 70
export const TASK_COMMAND_COOLDOWN_MS = 5000
export const TASK_ROTATION_INTERVAL_MS = 10000

export function createViewerTask(
  userId: string,
  displayName: string,
  usernameColor: string | undefined,
  now: number,
): ViewerTask {
  return {
    userId,
    username: userId,
    displayName,
    usernameColor,
    currentTask: null,
    lastTask: null,
    lastWorkTask: null,
    status: "cleared",
    submittedAt: now,
    completedToday: 0,
  }
}
