-- Neon schema for the overlay's persistent data.
--
-- Migrated off Supabase because its free tier pauses a project after ~7 days of
-- inactivity and requires a manual click to resume. That pause is what caused the
-- Board of Guardians to come up empty mid-stream. Neon idles the compute too, but
-- auto-resumes on the next query, so no weekly babysitting.
--
-- No RLS here. Both tables are only ever read/written by server-side API routes
-- using the connection string, never from the browser. The previous setup had RLS
-- enabled with zero policies, which silently returned 0 rows to the anon key.

-- Permanent record: anyone who has ever hit the 50-flower Guardian threshold.
CREATE TABLE IF NOT EXISTS guardians (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL,
  flower_count INTEGER NOT NULL DEFAULT 50,
  achieved_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Usernames are always lowercased by the API before read or write, so a plain
-- unique index is enough to guarantee one row per viewer. This is what makes the
-- atomic upsert in /api/guardians/add safe under concurrent picks.
CREATE UNIQUE INDEX IF NOT EXISTS guardians_username_key ON guardians (username);

-- The board is always ordered by flower_count DESC.
CREATE INDEX IF NOT EXISTS guardians_flower_count_idx ON guardians (flower_count DESC);

-- Running trivia leaderboard.
CREATE TABLE IF NOT EXISTS trivia_scores (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS trivia_scores_username_key ON trivia_scores (username);

CREATE INDEX IF NOT EXISTS trivia_scores_score_idx ON trivia_scores (score DESC);
